services:
  llm:
    command: ["uvicorn", "main:app", "--host", "0.0.0.0"]
    # command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0"]
    # ports:
    #   - "8080:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    # profiles:
    #   - disabled

  ollama:
    ports:
      - "11434:11434"
      
  cloudflare_tunnel:
    profiles:
      - disabled