services:
  agent:
    image: agent-service
    restart: on-failure:5
    volumes:
      - backend_data:/backend_data
      - ./env/:/backend_data/env/
      - ./logs/:/backend_data/logs/
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-backend_database}
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - POSTGRES_HOST=${POSTGRES_HOST:-database}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_DB=${REDIS_DB:-0}
      - GOOGLE_API_KEY
    depends_on:
      - database
    deploy:
      resources:
        limits:
          cpus: '4.00'
          memory: 4GB
        reservations:
          cpus: '2.00'
          memory: 2GB
          devices:
            - driver: nvidia
              capabilities: [gpu]
    labels:
      - "traefik.enable=true"
      # Docs Router
      - "traefik.http.services.agent-api.loadbalancer.server.port=8000"
      - "traefik.http.routers.agent-api.rule=PathPrefix(`/agent-service/agent`) || Header(`X-Service-Name`, `agent-service`)"
      - "traefik.http.routers.agent-api.entrypoints=api-t"
    networks:
      - gateway_net
      - local_net

  redis:
    image: redis:latest
    restart: on-failure:5
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1GB
        reservations:
          cpus: '0.50'
          memory: 512MB
    networks:
      - local_net


  database:
    image: pgvector/pgvector:pg18
    restart: on-failure:5
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-backend_database}
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
    volumes:
      - postgres_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-backend_database}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1GB
        reservations:
          cpus: '0.50'
          memory: 512MB
    # labels:
      # - "traefik.enable=true"
      # - "traefik.http.routers.database.rule=Host(`agent-service_db-t.truong51972.id.vn`)"
      # - "traefik.http.routers.database.entrypoints=agent-service_db-t"
      # - "traefik.http.services.database.loadbalancer.server.port=5432"
    networks:
      - gateway_net
      - local_net

volumes:
  backend_data:
  postgres_db:
  redis_data:

networks:
  gateway_net:
    external: true
  local_net:
    driver: bridge