services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure:5
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-frontend}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - local_net

  django-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-dev-server
    restart: on-failure:5
    depends_on:
      db:
        condition: service_healthy
    entrypoint: /bin/sh -c
    command: >
      "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/app
      - ./static:/app/staticfiles
    environment:
      - DJANGO_SETTINGS_MODULE=APIT.settings
      - POSTGRES_DB=${POSTGRES_DB:-frontend}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - PRODUCTION_ENVIRONMENT
    env_file:
      - .env
    stdin_open: true
    tty: true
    labels:
      - "traefik.enable=true"
      # Docs Router
      - "traefik.http.services.frontend.loadbalancer.server.port=8001"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=api-t"
    networks:
      - local_net
      - gateway_net


volumes:
  postgres_data:

networks:
  gateway_net:
    external: true
  local_net:
    driver: bridge